---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Updates Python dependencies and raises a pull request with changes
name: 'Dependencies Updates'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'
  push:
    branches:
      - 'main'
      - 'master'
    paths:
      - '**'
      - '!.github/**'
      - '!.*'
      - '!pdm.lock'
      - '!tox.ini'

env:
  python-version: 3.11

permissions: {}

jobs:
  python-dependencies:
    name: 'Dependencies Updates'
    runs-on: 'ubuntu-latest'
    permissions:
      # IMPORTANT: mandatory to raise the PR
      id-token: write
      pull-requests: write
      repository-projects: write
      contents: write
    timeout-minutes: 10
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: lfreleng-actions/python-dependencies-update-action@f81d67225c672cddbe56d8234b69868a797c75e7 # v0.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
