---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 3
    # yamllint disable rule:line-length
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Running local action: ${{ github.repository }} [v1.0.0]"
        id: first
        uses: ./
        with:
          tag: 'v1.0.0'

      - name: "Running local action: ${{ github.repository }} [v1.1.0/minor/production]"
        id: second
        uses: ./
        with:
          tag: 'v1.1.0'
          increment: 'minor'
          type: 'production'

      - name: "Running local action: ${{ github.repository }} [v1.1.0-dev3/minor/development]"
        id: third
        uses: ./
        with:
          tag: 'v1.1.0-dev3'
          increment: 'minor'
          type: 'development'

      - name: "Running local action: ${{ github.repository }}"
        id: fourth
        uses: ./
        with:
          tag: 'v1.1.0'
          increment: 'minor'
          type: 'production'

      - name: "Running local action: ${{ github.repository }} [v2.2.0-dev1/minor/development]"
        id: fifth
        uses: ./
        with:
          tag: 'v1.1.0-dev3'
          increment: 'major'
          type: 'production'

      - name: "Validate local action: ${{ github.repository }}"
        shell: bash
        run: |
          # Local action validation
          echo 'Placeholder validation step'
